spring:
  application:
    name: payment-service

  config:
    import: "optional:configserver:"      # Config Server optional

  cloud:
    config:
      uri: "config-server"
      fail-fast: false
      retry:
        max-attempts: 1
        initial-interval: 1000
  management:
    tracing:
      sampling:
        probability: 1.0  # 개발 중 모든 요청 추적
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

  logging:
    pattern:
      level: "%5p [${spring.application.name:}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

payment:
  toss:
    url: https://api.tosspayments.com/v1/payments
    secret-key: ${TOSS_SECRET_KEY:dummy-toss-secret}
    client-key: ${TOSS_CLIENT_KEY:dummy-toss-client}

  nicepay:
    name: NICEPAY
    api-url: https://api.nicepay.co.kr/v1/payments
    sandbox-url: https://sandbox-api.nicepay.co.kr/v1/payments
    client-key: ${NICEPAY_CLIENT_KEY:dummy-nicepay-client}
    secret-key: ${NICEPAY_SECRET_KEY:dummy-nicepay-secret}
    sandbox: true
