spring:
  application:
    name: payment-service

  config:
    import: "configserver:"      # Config Server에서 설정 가져옴

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        max-attempts: 3
        initial-interval: 1000



  payment:
    toss:
      secret-key: test_ck_ex6BJGQOVDKaLOgRQWZB3W4w2zNb
      url: https://api.tosspayments.com/v1/payments
