###############################
# 배포/전체 서비스 Docker 실행 용도 #
###############################

# EUREKA --------------------------------------------------
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka

# SPRING --------------------------------------------------
spring:
  jpa:
    hibernate:
      # 운영 안정성 등을 고려하여 배포 또는 테스트환경에서 DB가 변경되지 않고 검증만 하도록 합니다.
      ddl-auto: validate

# MONITORING -----------------------------------------------
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
